---
functional:
  - Пользователь должен иметь возможность авторизоваться на сайте через электронную почту и пароль (авторизация).
  - Пользователь должен иметь возможность зарегистрироваться на сайте (авторизация).
  - При регистрации пользователя должна быть проверка уникальности никнейма (авторизация).
  - Никнейм должен быть ограничен по количеству символов (авторизация).
  - Электронная почта должна проверяться на корректность (авторизация).
  - Пароль должен иметь ограничение по количеству символов (авторизация).
  - Пароль должен соответствовать требованиям безопасности - минимум одна заглавная буква, минимум одна буква нижнего регистра, спецсимволы (авторизация).
  - При создании пароля должно существовать второе поле - повторите пароль (авторизация).
  - Пароли должны совпадать (авторизация).
  - Пользователь должен иметь возможность посмотреть/скрыть пароль (авторизация).
  - Зарегистрированный пользователь должен иметь возможность восстановить пароль (авторизация).
  - Пользователь не может авторизоваться, если все поля не заполнены (авторизация).
  - Пользователь не может зарегистрироваться, если все поля не заполнены (авторизация).
  - У чата есть два канала - General и Notification (чат).
  - Существующие каналы нельзя удалить или переименовать (чат).
  - Пользователь должен иметь возможность отправлять сообщения в чат (чат).
  - Другие пользователи могут видеть имя отправителя сообщения (чат).
  - Пользователь может напрямую отвечать другому пользователю в чате (чат).
  - Если сообщений в чате слишком много, то появляется полоса прокрутки (чат).
  - При переключении в канал, отображаются последние сообщения в чате (чат).
  - При клике на автора сообщения появляется всплывающее окошко с возможными взаимодействиями с пользователем (чат).
  - Никнейм пользователя можно скопировать (чат).
  - Есть кнопка "информация о пользователе" с переадресацией на его страницу (чат).
  - Есть кнопка "подписаться" на пользователя (чат).
  - Пользователю можно отправить личное сообщение (чат).
  - Пользователь может видеть, кто из других пользователей сейчас онлайн (чат).
  - При клике на пользователя появляется модальное окно с информацией о пользователе и возможностью отправить ему приглашение на игру (чат).
  - Пользователю доступна страница "Users rating" (рейтинг пользователей).
  - Пользователь может просматривать рейтинг игроков за неделю (рейтинг пользователей).
  - Пользователь может просматривать рейтинг игроков за месяц (рейтинг пользователей).
  - Пользователь может просматривать рейтинг игроков за все время (рейтинг пользователей).
  - Рейтинг обновляется автоматически в соответствии с успехами пользователей (рейтинг пользователей).
  - Можно настроить сортировку по месту, рейтингу, сыгранным играм, дате авторизации на сайте (рейтинг пользователей).
  - Можно настроить фильтрацию отображения пользователей по их количеству на странице (рейтинг пользователей).
  - Можно выбрать/скрыть отображение ботов среди пользователей (рейтинг пользователей).
  - На странице есть поисковая строка по никнейму пользователя (рейтинг пользователей).
  - Пользователю доступна страница "Tasks" (задания).
  - Пользователь может просматривать задания, созданные другими пользователями (задания).
  - Пользователь может создавать свои задания (задания).
  - Название задания должно быть уникальным (задания).
  - Можно выбрать видимость задания "hidden/public" (задания).
  - Можно выбрать уровень сложности (задания).
  - Операция не выполнится, если не будут заполнены все поля (задания).
  - Пользователь может создавать task pack (задания).
  - При создании название должно быть уникальным (задания).
  - Можно выбрать видимость "hidden/public" (задания).
  - При создании можно вписать id заданий, которые нужно объединить (задания).
  - Созданные task и task pack можно редактировать/удалить (задания).
  - Операция не выполнится, если не будут заполнены все поля (задания).
  - Пользователю доступна страница "Турниры/Tournaments" (турниры).
  - Пользователь может видеть список турниров, которые проходят сейчас (турниры).
  - Пользователь может присоединиться к турнирам, которые проходят сейчас (турниры).
  - Пользователь может покинуть турнир в любой момент (турниры).
  - Пользователь может видеть список завершенных турниров (турниры).
  - У пользователя есть возможность создавать турниры (турниры).
  - Пользователь может выбрать тип турнира - individual/team/swiss/arena/versus (турниры).
  - Пользователь может добавить описание турнира (турниры).
  - Пользователь может установить дату и время начала турнира (турниры).
  - Пользователь может выбрать тип доступа к турниру - public/token (турниры).
  - Пользователь может настроить task strategy - random_per_game/random_per_round/sequential (турниры).
  - Пользователь может настроить score strategy - time_and_tests/win_loss/one_zero (турниры).
  - Пользователь может настроить task provider - level/task_pack/task_pack_per_round/all (турниры).
  - Пользователь может указать лимит по количеству пользователей для турнира (турниры).
  - Есть возможность выбрать язык программирования для турнира (турниры).
  - Есть возможность выбрать уровень сложности (турниры).
  - Есть возможность указать match timeout в секундах (турниры).
  - Есть возможность указать break duration в секундах (турниры).
  - Есть возможность установить таймер для турнира (турниры).
  - Есть возможность создать турнир с чатом (турниры).
  - В чате турнира пользователь может отправлять сообщения в чат (турниры).
  - В чате турнира пользователи могут видеть имя отправителя сообщения (турниры).
  - В чате турнира пользователь может отвечать другому пользователю (турниры).
  - Если сообщений в чате слишком много, то появляется полоса прокрутки (турниры).
  - Пользователь, создавший турнир, может удалять из него других участников (турниры).
  - Пользователь может покинуть турнир самостоятельно в любой момент (турниры).
  - Пользователь, создавший турнир, может его удалить (турниры).
  - Турнир с типом доступа public доступен всем пользователям (турниры).
  - Турнир с типом доступа token доступен пользователю, который его создал, и участникам данного турнира (турниры).
  - На главной странице в правом верхнем углу пользователю доступен личный кабинет (ЛК).
  - В личном кабинете корректно отображается фото пользователя (ЛК).
  - Фото пользователя можно заменить (ЛК).
  - В личном кабинете пользователю доступны настройки (ЛК).
  - В настройках доступна опция смены никнейма (ЛК).
  - В настройках пользователь может выбрать язык программирования как «Weapon» (ЛК).
  - В настройках пользователь может выбрать "Clan" (ЛК).
  - В настройках пользователь может выбрать "Sound type" (ЛК).
  - В настройках пользователь может выбрать "Sound level" (ЛК).
  - В настройках при выборе "Sound level" есть кнопка Save (ЛК).
  - В настройках пользователь может добавить ссылки на свои аккаунты в GitHub и Discord (ЛК).
  - Пользователь может выйти из аккаунта (ЛК).
  - В личном кабинете отображается статистика пользователя и завершенные игры (ЛК).
  - Пользователь может самостоятельно создать игру (игра).
  - Пользователь может самостоятельно настраивать параметры при создании новой игры (игра).
  - Пользователь может выбрать уровень игры (игра).
  - Пользователь может выбрать тип игры - с другим пользователем /с другом / с ботом (игра).
  - При выборе типа игры "с другим пользователем" появляется поисковая строка для ввода никнейма (игра).
  - Пользователь может выбрать игровую задачу по названию (игра).
  - Пользователь может выбрать игровую задачу по тэгам (игра).
  - Пользователь может установить временные рамки для игры (игра).
  - Пользователь перенаправляется на страницу созданной игры с учетом указанных им параметров (игра).
  - На странице созданной игры появляется модальное окно с гайдом - карта игровой страницы (игра).
  - Есть возможность выбора темы отображения игры - Light/Dark (игра).
  - Во время игры можно выбрать язык программирования для решения задачи (игра).
  - Во время игры пользователю доступно игровое текстовое поле для написания решения задачи (игра).
  - Все строчки игрового текстового поля пронумерованы (игра).
  - Игровое текстовое поле принимает символы русского/английского языка и спецсимволы (игра).
  - Во время игры пользователь может видеть игровое поле противника в режиме онлайн (игра).
  - Во время игры можно сбросить изменения игрового поля к первоначальному виду (игра).
  - Пользователь видет отсчет времени во время игры (игра).
  - Пользователь может сдаться во время игры (игра).
  - Пользователь может самостоятельно проверить свое решение (игра).
  - Если решение задачи было неверным, игра выдает отчет об ошибке (игра).
  - Все проверки игры и действия пользователей происходят в режиме онлайн (игра).
  - Победа присуждается пользователю, который первым правильно решил задачу (игра).
  - За победу пользователю начисляются очки (игра).
  - Правильность решения задачи определяет приложение (игра).
  - После победы/поражения в игре пользователю показывается победное модальное окно (игра).
  - После победы/поражения в игре, возможно сделать "Rematch" игры (игра).
  - Игра завершается при победе/самостоятельной сдаче/победе противника/сдаче противника/завершении времени (игра).
  - Функция "Rematch" игры запускает новую игру с настройками предыдущей, с тем же противником (игра).
  - Игру "Game type" = "with other users" можно отменить до тех пор, пока к ней не присоединится другой пользователь (игра).
  - Пользователю доступна отправка обратной связи в окно "Send feedback" (игра).
  - Окно обратной связи разделено на 3 категории - "Bug"/"Improvement"/"Feature" (игра).
  - Пользователь может отправлять приглашение на игру другому пользователю (игра).
  - Пользователь может принимать приглашение на игру от другого пользователя (игра).
  - Пользователь может отклонить приглашение на игру от другого пользователя (игра).
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - Пользователь может принимать участие одновременно только в одной игре.
  - Нельзя создать турнир с прошедшей датой начала.
  - Контент на сайте должен отображаться без орфографических/грамматических ошибок.
